version: '3.8'
services:
  productivity-hub-frontend:
    build:
      context: ./ProductivityHub-FE
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  productivity-hub-backend:
    build:
      context: ./ProductivityHub-BE
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
